default: &postgresql
 adapter: postgresql
 host: ''
 pool: 5
 timeout: 5000

 
 
 
development:
 <<: *postgresql
 database: expense_development
 
test:
 <<: *postgresql
 database: expensify-rails-5_test
 
production:
 <<: *postgresql
 database: expensify-rails-5_production